name: CI Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with project's Gradle wrapper
        run: ./gradlew clean build
      - name: Run under this JDK
        run: java -jar build/libs/*.jar one 2 333
